xinzhi:
  uid: U17A127EEB
  key: swtu8zfjnoqwpfjc
  weatherApi:  https://api.seniverse.com/v3/weather/now.json

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 3000
    jedis:
      pool:
        max-active: 20
        max-wait: 1000
        max-idle: 20

wechat:
  AppId: wxa5da69153bc4b178
  AppSecret: f9355ca6fdddd846a969bc4382655122
  createMenu: https://api.weixin.qq.com/cgi-bin/menu/create
  myUserName: gh_b06ebfb5540f