server:
  port: 8001
  servlet:
    context-path: /weather

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 3000
    jedis:
      pool:
        max-active: 20
        max-wait: 1000
        max-idle: 20
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/weather?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 50
    minIdle: 50
    maxActive: 50
    maxWait: 500
    testOnBorrow: true #从池中获取连接时进行验证
    testOnCreate: false #新建一个连接时验证
    testOnReturn: false #将连接放回池中时验证


    timeBetweenEvictionRunsMillis: 0 #配置间隔多久才进行一次检测，0表示禁用
    minEvictableIdleTimeMillis: 0 # 配置一个连接在池中最小生存的时间，单位是毫秒，0表示禁用
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

wechat: #微信配置
  appId: wxa5da69153bc4b178
  appSecret: f9355ca6fdddd846a969bc4382655122
  createMenuUrl: https://api.weixin.qq.com/cgi-bin/menu/create
  myUserName: gh_b06ebfb5540f

gaode: #高德配置
  key: b63a0e56098f9dcfa0fecb34da816edd
  regeoApi: http://restapi.amap.com/v3/geocode/regeo

xinzhi: #心知天气
  uid: U17A127EEB
  key: swtu8zfjnoqwpfjc
  weatherApi:  https://api.seniverse.com/v3/weather/now.json

mybatis:
  type-aliases-package: com.xiao.weather.entity;com.xiao.weather.common.vo;
  mapper-locations: classpath:mappers/*.xml


